name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Используем отдельный секрет для MariaDB root-пароля
      DB_PASS: ${{ secrets.DB_ROOT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
  
      - name: Set masked outputs
        run: echo "::add-mask::$DB_PASS"
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan -var="db_root_password=$DB_PASS"
      
      - name: Terraform Apply
        run: terraform apply -var="db_root_password=$DB_PASS" -auto-approve
      
      - name: Check Web Container 
        run: curl -s 127.0.0.1:8080 | grep -q 'My First and Lastname'
        
      - name: Wait for MariaDB container
        run: |
          i=0
          while ! mysql -h 127.0.0.1 2>&1 | grep -q 'password'
          do
            if [ $i -eq 10 ]
            then
              echo 'Timed out waiting for MariaDB container'
              exit 1
            fi
            i=$((i+1))
            sleep 1
          done
  
      - name: Check Database Container 
        run: mysql -h 127.0.0.1 -u root -p$DB_PASS -e 'select version();'
  
      - name: Stop Containers 
        run: docker stop $(docker ps -q)
